name: bluetooth_ym
description: A dart project to manage bluetooth.
repository: https://github.com/YannMancel/bluetooth_ym

version: 0.1.0

environment:
  sdk: '>=2.18.0 <3.0.0'

dependencies:
  flutter_blue_plus: ^1.3.1
  freezed_annotation: ^2.1.0
  meta: ^1.8.0

dev_dependencies:
  build_runner: ^2.2.1
  freezed: ^2.1.0+1
  lints: ^2.0.0
  test: ^1.21.6
